"""
Keep the column table in UTC's README identical to COLUMNS.md.

COLUMNS.md is itself generated from ``transect.OUTPUT_COLUMNS``, so there is one
authored description per column and everything else derives from it. That matters
here more than it usually would: a duplicated table of forty-four columns is
exactly the kind of thing that quietly stops matching the code, and this project
has already been bitten once by two copies of one rule drifting apart.

    python tools/column_docs.py            # print what the section should say
    python tools/column_docs.py --write    # update UTC/README.md in place

The test suite runs the same comparison, so a column added or reworded without
refreshing the README fails there rather than misleading a reader later.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COLUMNS_MD = ROOT / "mcap_to_csv" / "COLUMNS.md"
UTC_README = ROOT / "UTC" / "README.md"

START = "<!-- transect-columns: generated by mcap_to_csv/tools/column_docs.py -->"
END = "<!-- /transect-columns -->"


def render() -> str:
    """The column tables from COLUMNS.md, as one block for UTC's README."""
    text = COLUMNS_MD.read_text(encoding="utf-8")
    body = text.split("## The columns", 1)[1].split("## Rules that apply", 1)[0]

    out: list[str] = [START, ""]
    for chunk in re.split(r"^### ", body, flags=re.M)[1:]:
        title, _, rest = chunk.partition("\n")
        rows = [ln for ln in rest.splitlines() if ln.startswith("|")]
        if not rows:
            continue
        out.append(f"**{title.strip()}**")
        out.append("")
        out.extend(rows)
        out.append("")
    out.append(END)
    return "\n".join(out)


def current() -> str | None:
    """The block as it currently stands in UTC's README."""
    text = UTC_README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        return None
    return START + text.split(START, 1)[1].split(END, 1)[0] + END


def write() -> bool:
    text = UTC_README.read_text(encoding="utf-8")
    block = render()
    if START in text and END in text:
        before = text.split(START, 1)[0]
        after = text.split(END, 1)[1]
        updated = before + block + after
    else:
        raise SystemExit(
            f"markers not found in {UTC_README}. Add:\n  {START}\n  {END}"
        )
    if updated == text:
        return False
    UTC_README.write_text(updated, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="update UTC/README.md instead of printing")
    args = ap.parse_args(argv)
    if args.write:
        print("updated" if write() else "already up to date")
    else:
        print(render())
    return 0


if __name__ == "__main__":
    sys.exit(main())
